name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}  # Utilise le nom d'utilisateur de l'acteur (vous)
        password: ${{ secrets.GITHUB_TOKEN }}  # Utilise le GITHUB_TOKEN pour l'authentification

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/audri1234/ue19-lab-05:latest .

    - name: Push Docker image
      run: |
        docker push ghcr.io/audri1234/ue19-lab-05:latest
